CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) UNIQUE NOT NULL,
    year_of_birth int NOT NULL
);

CREATE TABLE Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    date_of_receipt TIMESTAMP,
    person_id int references Person(id) ON DELETE SET NULL
);

INSERT INTO Person(full_name, year_of_birth) VALUES('Петров Игорь Петрович', 1985);
INSERT INTO Person(full_name, year_of_birth) VALUES('Николаев Кирилл Игоревич', 1970);
INSERT INTO Person(full_name, year_of_birth) VALUES('Артюхова Наталья Климовна', 2001);
INSERT INTO Person(full_name, year_of_birth) VALUES('Рамазанов Рамазан Арсенович', 1984);
INSERT INTO Person(full_name, year_of_birth) VALUES('Любимова Дарья Павловна', 1999);

INSERT INTO Book(title, author, year) VALUES('Преступление и наказание','Федор Достоевский', 1866);
INSERT INTO Book(title, author, year) VALUES('Мастер и Маргарита','Михаил Булгаков', 1940);
INSERT INTO Book(title, author, year) VALUES('Мертвые души','Николай Гоголь', 1842);
INSERT INTO Book(title, author, year) VALUES('Герой нашего времени','Михаил Лермонтов', 1840);
INSERT INTO Book(title, author, year) VALUES('Доктор Живаго','Борис Пастернак', 1955);
INSERT INTO Book(title, author, year) VALUES('Униженные и оскорбленные','Федор Достоевский', 1861);
INSERT INTO Book(title, author, year) VALUES('Рассказы','Антон Чехов', 1885);
INSERT INTO Book(title, author, year) VALUES('Евгений Онегин','Александр Пушкин', 1837);